location:


message:
  invalid-command: "&7(&b/Dropparty&7) &cInvalid command!"
  missing-permission-player: "&7(&b/Dropparty&7) &cYou don't have permission to use this command!"
  missing-permission-admin: "&7(&b/Dropparty&7) &cYou don't have permission to use this command!"
  dropparty-start: "&7(&b/Dropparty&7) &cDropparty event has been started."
  dropparty-ended: "&7(&b/Dropparty&7) &cDropparty event has been ended."
  dropparty-reset: "&7(&b/Dropparty&7) &cDropPart reset!"
  dropparty-cancel-success: "&7(&b/Dropparty&7) &chave been cancelled by &e&l%admin%"
  dropparty-cancel-failed: "&7(&b/Dropparty&7) &cDropParty haven't started yet!"
  dropparty-gui-admin: "&7DropPatrty Admin"
  dropparty-gui-player: "&7DropPatrty Donation"