name: 'Feature'
description: 'Select if you want an feature in our plugin.'
title: "[FEATURE] "
labels: [ 'feature' ]
body:
  - type: 'textarea'
    id: 'details'
    attributes:
      label: 'Feature Details'
      description: 'Describe your idea and how it works .'
    validations:
      required: true