# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/softprops/action-gh-release

name: Plugin Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_n_release:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          generate_release_notes: true
          files: |
            target/DropParty-$RELEASE_VERSION.jar
            LICENSE